name: Build

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          make build-dependencies
      - name: Build Distribution
        run: |
          make build