name: Doc

on:
  release:
    types: [published]
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          make doc-dependencies
      - name: Documentation build
        run: |
          make doc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
        with:
          publish_branch: doc
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/sphinx
          force_orphan: true
