name: Sec

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          make sec-dependencies
      - name: Security Scan
        run: |
          make sec