name: Test

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        make test-dependencies
    - name: Unit Test Matrix
      run: |
        make test
