name: Test

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        # Install the python interpreters for running the test matrix
        apt install software-properties-common
        add-apt-repository ppa:deadsnakes/ppa
        apt update
        apt install python3.9 -y
        apt install python3.10 -y
        apt install python3.11 -y
        apt install python3.12 -y
        apt install python3.13 -y

        # Install the python dependencies for running the tests
        make test-dependencies

    - name: Unit Test Matrix
      run: |
        # Run the unit test matrix
        make test
